import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gradient-to-br from-white to-gray-100 min-h-screen`}>
        {/* Navbar */}
        <nav className="w-full bg-gray-800 shadow-sm py-4 px-8 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <img src="/logo.svg" alt="Logo" className="h-8 w-8" />
            <span className="font-bold text-lg text-white">Pantelotteri</span>
          </div>
          <div className="flex gap-6">
            <a href="/" className="text-gray-400 hover:text-green-600 font-medium">Oversikt</a>
            <a href="#" className="text-gray-400 hover:text-green-600 font-medium">Trekning</a>
            <a href="#" className="text-gray-400 hover:text-green-600 font-medium">Statistikk</a>
          </div>
        </nav>

        {/* Main content */}
        <div className="flex flex-col min-h-[80vh]">
          {children}
        </div>

        {/* Footer */}
        <footer className="w-full bg-black border-t mt-12 py-4 text-center text-white text-sm">
          © 2025 Pantelotteri. Laget for eksamen.
        </footer>
      </body>
    </html>
  );
}